---
sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
